---
name: Report Failure and Notify Slack
description: |
    This GitHub composite action imports secrets from HashiCorp Vault and sends a Slack notification in case of a workflow failure.
    It helps automate incident reporting and ensures timely notifications to the relevant Slack channel.
    Use it with `if: failure()`

inputs:
    vault_addr:
        description: The address of the Vault instance
        required: true
    vault_role_id:
        description: The role ID used for authentication with Vault
        required: true
    vault_secret_id:
        description: The secret ID used for authentication with Vault
        required: true
    slack_channel_id:
        description: The Slack channel ID where the notification will be sent.
        default: C076N4G1162 # infraex-alerts
    slack_mention_people:
        description: The Slack people to mention in the notification.
        default: '@infraex-medic'
    disable_silence_check:
        description: |
            Disable silence check.
            By default, alerts can be disabled by creating an issue in the repository
            with the label alert-management and with the title:
            silence: name of your workflow
        required: false
        default: 'false'

runs:
    using: composite
    steps:
        - name: Generate token for GitHub
          id: generate-github-token
          if: ${{ inputs.disable_silence_check == 'false' }}
          uses: camunda/infra-global-github-actions/generate-github-app-token-from-vault-secrets@a969eec70a9f47d8b77a13a3c052c9d9c8376390 # main
          with:
              github-app-id-vault-key: GITHUB_APP_ID
              github-app-id-vault-path: secret/data/products/infrastructure-experience/ci/common
              github-app-private-key-vault-key: GITHUB_APP_PRIVATE_KEY
              github-app-private-key-vault-path: secret/data/products/infrastructure-experience/ci/common
              vault-auth-method: approle
              vault-auth-role-id: ${{ inputs.vault_role_id }}
              vault-auth-secret-id: ${{ inputs.vault_secret_id }}
              vault-url: ${{ inputs.vault_addr }}
              # we generate a token with access to all assigned repos for the analyzer trigger
              owner: camunda
              repositories: '!all'

        - name: Check for Silence Issue
          id: silence-check
          if: ${{ inputs.disable_silence_check == 'false' }}
          shell: bash
          continue-on-error: true
          run: |
              ISSUE_TITLE="silence: ${{ github.workflow }}"
              ISSUE_SEARCH=$(gh issue list --repo ${{ github.repository }} --state open --search "$ISSUE_TITLE in:title" --label "alert-management" --json number,title,url)
              ISSUE_COUNT=$(echo "$ISSUE_SEARCH" | jq '. | length')

              if [ "$ISSUE_COUNT" -gt 0 ]; then
                ISSUE_TITLE=$(echo "$ISSUE_SEARCH" | jq -r '.[0].title')
                ISSUE_URL=$(echo "$ISSUE_SEARCH" | jq -r '.[0].url')
                echo "Issue found: $ISSUE_TITLE - $ISSUE_URL . Skipping notification. Close this issue to re-enable notifications."
                exit 0
              else
                echo "No silence issue found, triggering the slack alert."
                exit 1
              fi
          env:
              GITHUB_TOKEN: ${{ steps.generate-github-token.outputs.token }}

        - name: Import Secrets
          id: secrets
          if: ${{ steps.silence-check.outcome != 'success' }} # in case of success it means that a silence issue exists
          uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3
          with:
              url: ${{ inputs.vault_addr }}
              method: approle
              roleId: ${{ inputs.vault_role_id }}
              secretId: ${{ inputs.vault_secret_id }}
              exportEnv: false
              secrets: |
                  secret/data/products/infrastructure-experience/ci/common SLACK_BOT_TOKEN;

        - name: Notify in Slack in case of failure
          id: slack-notification
          if: ${{ steps.silence-check.outcome != 'success' }} # in case of success it means that a silence issue exists
          uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
          with:
              method: chat.postMessage
              token: ${{ steps.secrets.outputs.SLACK_BOT_TOKEN }}
              payload: |
                  {
                    "channel" : "${{ inputs.slack_channel_id }}",
                    "unfurl_links": false,
                    "unfurl_media": false,
                    "text": "${{ github.event.repository.name }} (${{ github.server_url }}/${{ github.repository }}) scheduled workflow: ${{ github.workflow }} failed! Please check: ${{ env.WORKFLOW_URL }} (cc ${{ inputs.slack_mention_people }})",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": ":automation-platform-failure: :mechanic: <${{ github.server_url }}/${{ github.repository }}|[${{ github.event.repository.name }}]> scheduled workflow: ${{ github.workflow }} failed! \n :link: Please check: ${{ env.WORKFLOW_URL }} \n (cc ${{ inputs.slack_mention_people }})"
                        }
                      }
                    ]
                  }
          env:
              WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

        - name: Trigger GHA Failure Log Analyzer
          id: trigger-analyzer
          if: ${{ steps.silence-check.outcome != 'success' }} # in case of success it means that a silence issue exists
          shell: bash
          run: |
              echo "Triggering GHA Failure Log Analyzer workflow..."
              gh workflow run "GHA Failure Log Analyzer" \
                --repo camunda/infraex-common-config \
                --field run_url="${{ env.WORKFLOW_URL }}" \
                --field slack_channel_id="${{ inputs.slack_channel_id }}" \
                --field slack_thread_ts="${{ steps.slack-notification.outputs.ts }}"

              echo "GHA Failure Log Analyzer triggered successfully"
          env:
              GITHUB_TOKEN: ${{ steps.generate-github-token.outputs.token }}
              WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
