-   id: update-action-readmes-docker
    name: Update GitHub Action READMEs
    entry: bash ./pre_commit_hooks/docker_update_action_readmes.sh
    language: system
    # Only runs when action files are modified
    files: ^\.github/actions/.+\.(yml|yaml)$
    pass_filenames: false # ensure single run
