---
name: Commit Changes If Actor Matches

description: |
    Checks if the pull request is from a specific actor, generates a GitHub token,
    and commits changes if the actor matches.

inputs:
    actor:
        description: The GitHub actor to check (e.g., renovate).
        required: true
    commit_message:
        description: The commit message to use.
        required: true
        default: 'chore: update files from gha'
    github_app_id_vault_key:
        description: Vault key for GitHub App ID.
        required: false
        default: GITHUB_APP_ID
    github_app_id_vault_path:
        description: Vault path for GitHub App ID.
        required: false
        default: secret/data/products/infrastructure-experience/ci/common
    github_app_private_key_vault_key:
        description: Vault key for GitHub App Private Key.
        required: false
        default: GITHUB_APP_PRIVATE_KEY
    github_app_private_key_vault_path:
        description: Vault path for GitHub App Private Key.
        required: false
        default: secret/data/products/infrastructure-experience/ci/common
    vault_auth_method:
        description: Vault authentication method.
        required: false
        default: approle
    vault_auth_role_id:
        description: Vault role ID for authentication.
        required: true
    vault_auth_secret_id:
        description: Vault secret ID for authentication.
        required: true
    vault_url:
        description: Vault URL.
        required: true

runs:
    using: composite
    steps:
        - name: Check if PR is from specified actor
          id: check-actor
          run: |
              if [[ "${{ github.actor }}" == "${{ inputs.actor }}" ]]; then
                echo "PR is from ${inputs.actor}"
                echo "should_commit=true" >> $GITHUB_ENV
              else
                echo "PR is not from ${inputs.actor}"
                echo "should_commit=false" >> $GITHUB_ENV
              fi

        - name: Generate token for GitHub
          if: env.should_commit == 'true'
          id: generate-github-token
          uses: camunda/infra-global-github-actions/generate-github-app-token-from-vault-secrets@f5bbd25c97507d6d2a884eebecaa804a6e34b15f # f5bbd25c97507d6d2a884eebecaa804a6e34b15f
          with:
              github-app-id-vault-key: ${{ inputs.github_app_id_vault_key }}
              github-app-id-vault-path: ${{ inputs.github_app_id_vault_path }}
              github-app-private-key-vault-key: ${{ inputs.github_app_private_key_vault_key }}
              github-app-private-key-vault-path: ${{ inputs.github_app_private_key_vault_path }}
              vault-auth-method: ${{ inputs.vault_auth_method }}
              vault-auth-role-id: ${{ inputs.vault_auth_role_id }}
              vault-auth-secret-id: ${{ inputs.vault_auth_secret_id }}
              vault-url: ${{ inputs.vault_url }}

        - name: Commit changes
          if: env.should_commit == 'true'
          uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
          with:
              commit_message: ${{ inputs.commit_message }}
          env:
              GITHUB_TOKEN: ${{ steps.generate-github-token.outputs.token }}
