---
name: Commit Changes

description: |
    Generates a GitHub token and commits changes.
    This action use https://github.com/stefanzweifel/git-auto-commit-action.

inputs:
    commit_message:
        description: The commit message to use.
        required: true
        default: 'chore: update files from gha'
    github_app_id_vault_key:
        description: Vault key for GitHub App ID.
        required: false
        default: GITHUB_APP_ID
    github_app_id_vault_path:
        description: Vault path for GitHub App ID.
        required: false
        default: secret/data/products/infrastructure-experience/ci/common
    github_app_private_key_vault_key:
        description: Vault key for GitHub App Private Key.
        required: false
        default: GITHUB_APP_PRIVATE_KEY
    github_app_private_key_vault_path:
        description: Vault path for GitHub App Private Key.
        required: false
        default: secret/data/products/infrastructure-experience/ci/common
    vault_auth_method:
        description: Vault authentication method.
        required: false
        default: approle
    vault_auth_role_id:
        description: Vault role ID for authentication.
        required: true
    vault_auth_secret_id:
        description: Vault secret ID for authentication.
        required: true
    vault_url:
        description: Vault URL.
        required: true

runs:
    using: composite
    steps:
        - name: Generate token for GitHub
          id: generate-github-token
          uses: camunda/infra-global-github-actions/generate-github-app-token-from-vault-secrets@f5bbd25c97507d6d2a884eebecaa804a6e34b15f # f5bbd25c97507d6d2a884eebecaa804a6e34b15f
          with:
              github-app-id-vault-key: ${{ inputs.github_app_id_vault_key }}
              github-app-id-vault-path: ${{ inputs.github_app_id_vault_path }}
              github-app-private-key-vault-key: ${{ inputs.github_app_private_key_vault_key }}
              github-app-private-key-vault-path: ${{ inputs.github_app_private_key_vault_path }}
              vault-auth-method: ${{ inputs.vault_auth_method }}
              vault-auth-role-id: ${{ inputs.vault_auth_role_id }}
              vault-auth-secret-id: ${{ inputs.vault_auth_secret_id }}
              vault-url: ${{ inputs.vault_url }}

        - name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
          with:
              commit_message: ${{ inputs.commit_message }}
          env:
              GITHUB_TOKEN: ${{ steps.generate-github-token.outputs.token }}
