---
name: pre-commit

on:
    pull_request:
    push:
        branches: [main]

jobs:
    lint:
        uses: ./.github/workflows/lint-global.yml
        with:
            check-renovate-lookup: true
        secrets: inherit
