---
name: Check TODOs via global workflow

# TODO: add a nice description so everyone understand the usage

on:
    issue_comment:
    pull_request:
        types: [opened, synchronize, reopened]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    call-todo-checker:
        if: |
            github.event_name == 'pull_request' ||
            (github.event_name == 'issue_comment' &&
            contains(github.event.comment.body, 'todo trigger'))
        uses: ./.github/workflows/todo-checker-global.yml
        secrets: inherit
