---
# This workflow triggers a scan of TODOs in the current pull request.
# For each TODO that is not marked to be ignored, it posts a comment.
# It helps ensure that no TODOs are accidentally left behind in merged PRs.

name: Check TODOs via global workflow


on:
    issue_comment:
        types: [created, edited]
    pull_request:
        types: [opened, synchronize, reopened]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    call-todo-checker:
        if: |
            github.event_name == 'pull_request' ||
            (github.event_name == 'issue_comment' &&
            contains(github.event.comment.body, 'update todos'))
        uses: ./.github/workflows/todo-checker-global.yml
        secrets: inherit
