---
# This workflow triggers a scan of TODOs in the current pull request.
# For each TODO that is not marked to be ignored, it posts a comment.
# It helps ensure that no TODOs are accidentally left behind in merged PRs.

name: Check TODOs via global workflow


on:
    pull_request:
        types: [opened, synchronize, reopened]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    call-todo-checker:
        uses: ./.github/workflows/todo-checker-global.yml
        secrets: inherit
