---
name: Check TODOs via global workflow

on:
    pull_request_review_comment:
        types: [created, edited, deleted]
    issue_comment:
        types: [created, edited, deleted]
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    call-todo-checker:
        uses: ./.github/workflows/todo-checker-global.yml
        secrets: inherit
